/**
 * Component exports.
 *
 * A diagram that ships in a product should be a component, not an `<img>`: it
 * stays selectable, it inherits the page's theme, and it does not need a build
 * step to re-render when the brand changes.
 */

import { buildSVG, themeVariables, uidFor } from "../render/svg.js";

const pascal = (value) =>
  String(value ?? "Diagram")
    .replace(/[^a-zA-Z0-9]+(.)?/g, (_, char) => (char ? char.toUpperCase() : ""))
    .replace(/^./, (char) => char.toUpperCase())
    .replace(/^\d+/, "") || "Diagram";

const kebab = (value) =>
  String(value ?? "diagram")
    .toLowerCase()
    .replace(/[^a-z0-9]+/g, "-")
    .replace(/^-|-$/g, "") || "diagram";

/** Split the rendered SVG into its opening tag and its body. */
function parts(diagram) {
  const svg = buildSVG(diagram, { interactive: false, uid: uidFor(diagram.id ?? diagram.title) });
  const open = svg.indexOf(">") + 1;
  return { svg, inner: svg.slice(open, svg.lastIndexOf("</svg>")) };
}

/**
 * A React component. Props override the title, description and any theme role,
 * so one exported diagram can serve light and dark without a second file.
 */
export function toReact(diagram, options = {}) {
  const name = options.name ?? pascal(diagram.title);
  const { inner } = parts(diagram);
  const uid = uidFor(diagram.id ?? diagram.title);

  // JSX needs camelCase attributes and expression-wrapped style objects, so the
  // body is emitted through dangerouslySetInnerHTML: it is generated markup,
  // not user input, and this keeps it byte-identical to the SVG export.
  return `// Generated by Diagram Studio. Re-export rather than editing by hand.
import React from "react";

const TITLE_ID = "${uid}-title";
const DESC_ID = "${uid}-desc";

const THEME = ${JSON.stringify(diagram.theme, null, 2)};

const BODY = ${JSON.stringify(inner)};

/**
 * ${diagram.title}
 * ${diagram.description ?? ""}
 */
export default function ${name}({ title, description, theme, className, ...rest }) {
  const tokens = { ...THEME, ...theme };
  const style = {
    ${themeVariables(diagram.theme, diagram.settings ?? {}, uid)
      .split(";")
      .filter(Boolean)
      .map((pair) => {
        const [key, value] = pair.split(/:(.+)/);
        return `"${key}": ${key.startsWith("--font") || key === "--sketch" || key === "--corner" ? JSON.stringify(value) : `tokens.${roleFor(key)} ?? ${JSON.stringify(value)}`}`;
      })
      .join(",\n    ")}
  };

  return (
    <svg
      xmlns="http://www.w3.org/2000/svg"
      className={className}
      viewBox="0 0 ${diagram.width} ${diagram.height}"
      width={${diagram.width}}
      height={${diagram.height}}
      role="img"
      aria-labelledby={\`\${TITLE_ID} \${DESC_ID}\`}
      style={style}
      {...rest}
    >
      <title id={TITLE_ID}>{title ?? ${JSON.stringify(diagram.title)}}</title>
      <desc id={DESC_ID}>{description ?? ${JSON.stringify(diagram.description ?? "")}}</desc>
      <g dangerouslySetInnerHTML={{ __html: BODY }} />
    </svg>
  );
}
`;
}

/** CSS custom property name back to its theme role. */
function roleFor(property) {
  const map = {
    "--paper": "paper",
    "--panel": "panel",
    "--ink": "ink",
    "--muted": "muted",
    "--accent": "accent",
    "--accent-2": "accent2",
    "--line": "line",
    "--line-strong": "lineStrong",
    "--on-accent": "onAccent",
  };
  return map[property] ?? "paper";
}

/**
 * A framework-free custom element. Drop the file in a `<script type="module">`
 * and use `<diagram-name></diagram-name>`; attributes override the theme roles.
 */
export function toWebComponent(diagram, options = {}) {
  const tag = options.tag ?? `diagram-${kebab(diagram.title)}`;
  const { svg } = parts(diagram);

  return `// Generated by Diagram Studio. Re-export rather than editing by hand.
// <${tag}></${tag}>
// Optional attributes: ${Object.keys(diagram.theme).filter((role) => typeof diagram.theme[role] === "string" && diagram.theme[role].startsWith("#")).join(", ")}

const TEMPLATE = document.createElement("template");
TEMPLATE.innerHTML = \`<style>:host{display:block;max-width:100%}svg{width:100%;height:auto;display:block}</style>${svg
    .replace(/`/g, "\\`")
    .replace(/\$\{/g, "\\${")}\`;

const ROLES = {
  paper: "--paper",
  panel: "--panel",
  ink: "--ink",
  muted: "--muted",
  accent: "--accent",
  accent2: "--accent-2",
  line: "--line",
  linestrong: "--line-strong",
  onaccent: "--on-accent",
};

class ${pascal(diagram.title)}Element extends HTMLElement {
  static get observedAttributes() {
    return Object.keys(ROLES);
  }

  connectedCallback() {
    if (!this.shadowRoot) {
      this.attachShadow({ mode: "open" }).append(TEMPLATE.content.cloneNode(true));
      for (const role of Object.keys(ROLES)) this.attributeChangedCallback(role, null, this.getAttribute(role));
    }
  }

  attributeChangedCallback(name, previous, value) {
    const svg = this.shadowRoot?.querySelector("svg");
    if (!svg || value === null) return;
    svg.style.setProperty(ROLES[name], value);
  }
}

customElements.define(${JSON.stringify(tag)}, ${pascal(diagram.title)}Element);
export default ${pascal(diagram.title)}Element;
`;
}
